import React from "react";
const Türkiyedata = {
  producttürk: [
    {
      id: 1,
      img: "https://imgcy.trivago.com/c_limit,d_dummy.jpeg,f_auto,h_1300,q_auto,w_2000/partnerimages/13/32/1332445474.jpeg",
      Imb: "8.7 - Mükemmel ",
      uzaklik: "Şehir merkezi 8.6 km uzaklıkta",
      yer: "Kempinski Hotel Barbaros Bay Bodrum",
      özellik: "2 yetişkin +1 çocuk  45 m2  ",
      içmekan: "stüdyo daire klimalı",
      tutar: "8.120TL",
      reklam: "vergiler ve ücretler dahildir",
      buradan:
        "https://www.kempinski.com/en/hotel-barbaros-bay?utm_medium=organic&utm_source=google&utm_campaign=KIBXN&utm_content=gmb&source=S308962248",
    },
    {
      id: 2,
      img: "https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_225,q_auto,w_225/itemimages/34/88/3488748_v19.jpeg",
      Imb: "9.5 - Mükemmel ",
      uzaklik: "Şehir merkezi 3.6 km uzaklıkta",
      yer: "Maxx Royal Kemer Resort",
      özellik: "2 yetişkin +1 çocuk  60 m2  ",
      içmekan: "stüdyo daire klimalı",
      tutar: "40.800TL",
      reklam: "vergiler ve ücretler dahildir",
      buradan: "https://www.maxxroyal.com",
    },
    {
      id: 3,
      img: "https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_225,q_auto,w_225/itemimages/12/14/121405_v13.jpeg",
      Imb: "9.3 - Mükemmel",
      uzaklik: "Şehir merkezi 10.8 km uzaklıkta",
      yer: "Ölüdeniz Blu Luxury Boutique Hotel ",
      özellik: "2 yetişkin +1 çocuk  55 m2  ",
      içmekan: "stüdyo daire klimalı",
      tutar: "3.141TL",
      reklam: "vergiler ve ücretler dahildir",
      buradan: "https://www.oludenizblu.com",
    },
    {
      id: 4,
      img: "https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_225,q_auto,w_225/itemimages/37/46/37461_v10.jpeg",
      Imb: "7.2",
      uzaklik: "Şehir merkezi 3.4 km uzaklıkta",
      yer: "Altin Yunus Hotel & Spa - Çeşme",
      özellik: "2 yetişkin +1 çocuk  35 m2  ",
      içmekan: "stüdyo daire klimalı",
      tutar: "2.574TL",
      reklam: "vergiler ve ücretler dahildir",
      buradan: "https://www.altinyunus.com.tr",
    },
    {
      id: 5,
      img: "https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_225,q_auto,w_225/itemimages/36/48/36487_v13.jpeg",
      Imb: "7.8 - İyi",
      uzaklik: "Plaja 0.5 km mesafede",
      yer: "Tuntaş Family Suit Kuşadası",
      özellik: "2 yetişkin +1 çocuk  35 m2  ",
      içmekan: "stüdyo daire klimalı",
      tutar: "626TL",
      reklam: "vergiler ve ücretler dahildir",
      buradan: "https://www.tuntashotels.com",
    },
  ],
};

export default Türkiyedata;
